version: '2'

services:
  db:
    volumes:
     - ./startupscripts:/docker-entrypoint-initdb.d
    environment:
     - MYSQL_ROOT_PASSWORD=pass
     - MYSQL_DATABASE=db
    image: mysql:latest
    networks:
     - roadiniserver_proxynet
    container_name: auth_db
  mygo:
    image: auth
    depends_on:
     - "db"
    volumes:
     - "../src:/app"
    networks:
     - roadiniserver_proxynet
    container_name: auth_api

networks:
    roadiniserver_proxynet:
        external: true

