version: '2'

services:
  db:
    ports:
     - "3306:3306"
    volumes:
     - ./startupscripts:/docker-entrypoint-initdb.d
    environment:
     - MYSQL_ROOT_PASSWORD=pass
     - MYSQL_DATABASE=db
    image: mysql:latest
  mygo:
    build: ../src/
    depends_on:
     - "db"
    volumes:
     - ./db_volume:/var
    command: ["/var/test_db_connection.sh", "db:3306"]
    ports:
     - "3000:3000"
